// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace ProjetoBlog.Models
{
    public partial class Post
    {
        [Display(Name = "Código")]
        public int Id { get; set; }
        [Display(Name = "Título")]
        [Required(ErrorMessage = "Escreva o Título")]
        public string Titulo { get; set; }
        [Display(Name = "Descrição")]
        [Required(ErrorMessage = "Escreva a Descrição")]
        public string Area { get; set; }
        [Display(Name = "Texto")]
        [Required(ErrorMessage = "Escreva o Texto")]
        public string Assunto { get; set; }
        public string Imagem { get; set; }
        public string Video { get; set; }
        [Display(Name = "Data e Hora da Postagem")]
        [Required(ErrorMessage = "Informe a Data e Hora da Postagem")]
        public DateTime DataPost { get; set; } = DateTime.Now;  

    }
}